services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        UUID: ${UUID}
        GID: ${GID}
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    depends_on:
      - db
    deploy:
      replicas: 1

  db:
    image: postgres:16.2
    deploy:
      replicas: 1
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - data_db:/var/lib/postgresql/data
      - ./postgres/pedido.sql:/docker-entrypoint-initdb.d/pedido.sql


networks:
  default:
    name: docker-php
    driver: bridge

volumes:
  data_db: