entryPoints:
  web:
    address: ":80"
api:
  insecure: true
  dashboard: true

log:
  level: DEBUG

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/conf
    watch: true