services:
  db:
    image: postgres:13.15
    expose:
      - 5432
    deploy:
      replicas: 1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: produtos
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/produtos.sql:/docker-entrypoint-initdb.d/produtos.sql

volumes:
  db_data:

networks:
  default:
    name: api
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24